In [2]:
#Numpy
import numpy as np
np.array(34)

array(34)

In [2]:
np.array([3,5,7,23])

array([ 3, 5, 7, 23])

In [6]:
np.array([[5,6,1,2],[2,3,5,8]])

array([[5, 6, 1, 2],
 [2, 3, 5, 8]])

In [11]:
x = np.array([4,6,8,2])
x.ndim
x.shape
x.size
x.dtype
type(x)

numpy.ndarray

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.full((2,4),3)

array([[3, 3, 3, 3],
 [3, 3, 3, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
 [0., 1., 0.],
 [0., 0., 1.]])

In [17]:
np.arange(1,20,2)

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

In [18]:
np.linspace(0,1,10)

array([0. , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
 0.55555556, 0.66666667, 0.77777778, 0.88888889, 1. ])

In [21]:
np.random.randint(2,10,9)

array([9, 4, 4, 4, 2, 6, 9, 6, 6])

In [22]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1]
a[5::]
a[3:7]
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]])

In [32]:
arr[0]
arr[1,2]
arr[2][2::]

array([11, 12])

In [33]:
arr1 = np.array([[3,4,5,2],[2,3,4,7],[9,8,1,4]])
arr1

array([[3, 4, 5, 2],
 [2, 3, 4, 7],
 [9, 8, 1, 4]])

In [34]:
arr>2

array([[False, False, True, True],
 [ True, True, True, True],
 [ True, True, True, True]])

In [35]:
arr>arr1

array([[False, False, False, True],
 [ True, True, True, True],
 [False, True, True, True]])

In [36]:
arr1[arr>2]

array([5, 2, 2, 3, 4, 7, 9, 8, 1, 4])

In [3]:
ab = np.random.randint(20, size=(4,5))
ab

array([[ 4, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [4]:
sub_ab = ab[:2,:3]
sub_ab

array([[4, 5, 2],
 [8, 7, 4]])

In [5]:
sub_ab[0,0] = 55
sub_ab

array([[55, 5, 2],
 [ 8, 7, 4]])

In [6]:
ab

array([[55, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [8]:
n = np.arange(1,10)
n
n.shape

(9,)

In [9]:
n_shape = n.reshape(3,3)
n_shape

array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [13]:
ab.reshape(-1)
ab
ab.flatten()

array([55, 5, 2, 10, 4, 8, 7, 4, 19, 8, 6, 13, 12, 10, 13, 9, 4,
 17, 5, 12])

In [3]:
#29 Jan
a = np.array([10,11,12])
b = np.array([20,21,22])
np.concatenate([a,b])

array([10, 11, 12, 20, 21, 22])

In [5]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[11,12,13],[14,15,16]])
np.concatenate([a1,a2])

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [11, 12, 13],
 [14, 15, 16]])

In [6]:
np.concatenate([a1,a2],axis=1)

array([[ 1, 2, 3, 11, 12, 13],
 [ 4, 5, 6, 14, 15, 16]])

In [7]:
n1 = np.array([1,3,5,7,34,645,12,21])
n1

array([ 1, 3, 5, 7, 34, 645, 12, 21])

In [11]:
q,w,e = np.split(n1,[3,6])
q

array([1, 3, 5])

In [12]:
w

array([ 7, 34, 645])

In [13]:
e

array([12, 21])

In [14]:
d1 = np.arange(28).reshape(7,4)
d1

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27]])

In [15]:
np.split(d1,[2,5])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27]])]

In [16]:
np.hsplit(d1,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21],
        [24, 25]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23],
        [26, 27]])]

In [17]:
np.sort(n1)

array([ 1, 3, 5, 7, 12, 21, 34, 645])

In [18]:
n1

array([ 1, 3, 5, 7, 34, 645, 12, 21])

In [20]:
n1.sort()
n1

array([ 1, 3, 5, 7, 12, 21, 34, 645])

In [21]:
-np.sort(-n1)

array([645, 34, 21, 12, 7, 5, 3, 1])

In [22]:
z = np.linspace(0,50,12,dtype="int").reshape(4,3)
z

array([[ 0, 4, 9],
 [13, 18, 22],
 [27, 31, 36],
 [40, 45, 50]])

In [23]:
m = np.array([1,0,-1])
m

array([ 1, 0, -1])

In [24]:
z + m

array([[ 1, 4, 8],
 [14, 18, 21],
 [28, 31, 35],
 [41, 45, 49]])

In [25]:
mat = np.array([1,2,3,4,5,6,7,8,9])
mat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
mat-5

array([-4, -3, -2, -1, 0, 1, 2, 3, 4])

In [29]:
mat *3

array([ 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [30]:
fun = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
fun

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [ 7, 8, 9],
 [10, 11, 12]])

In [31]:
np.add(fun,2)

array([[ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11],
 [12, 13, 14]])

In [32]:
np.subtract(fun,1)

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11]])

In [33]:
np.power(fun,2)

array([[ 1, 4, 9],
 [ 16, 25, 36],
 [ 49, 64, 81],
 [100, 121, 144]])

In [34]:
np.mean(fun)

6.5

In [35]:
np.sum(fun)

78

In [36]:
np.min(fun)

1

In [37]:
np.var(fun)

11.916666666666666

In [38]:
np.std(fun)

3.452052529534663

In [39]:
np.absolute(np.array([-1,2,-4,-49,-2]))

array([ 1, 2, 4, 49, 2])

In [40]:
np.log(fun)

array([[0. , 0.69314718, 1.09861229],
 [1.38629436, 1.60943791, 1.79175947],
 [1.94591015, 2.07944154, 2.19722458],
 [2.30258509, 2.39789527, 2.48490665]])

In [41]:
np.log10(fun)

array([[0. , 0.30103 , 0.47712125],
 [0.60205999, 0.69897 , 0.77815125],
 [0.84509804, 0.90308999, 0.95424251],
 [1. , 1.04139269, 1.07918125]])

In [ ]:
'''Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Go to the editor
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]'''

In [42]:
'''Write a NumPy program to create a 2d array with 1 on the border and 0 inside. Go to the editor
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

1 1 1 1 1
1 0 0 0 1
1 1 1 1 1'''
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
'''Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order. Go to the editor
Expected Output:
Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]'''

In [43]:
'''Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values. Go to the editor
Expected Output:
Original array elements:
[[ 12. 12.51]
[ 2.34 7.98]
[ 25.23 36.5 ]]
Convert float values to intger values:
[[12 12]
[ 2 7]
[25 36]]'''
import numpy as np
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print("Original array elements:")
print(x)
print("Convert float values to integer values:")
print(x.astype(int))

Original array elements:
[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
Convert float values to integer values:
[[12 12]
 [ 2  7]
 [25 36]]
