In [2]:
#Numpy
import numpy as np
np.array(34)

array(34)

In [2]:
np.array([3,5,7,23])

array([ 3, 5, 7, 23])

In [6]:
np.array([[5,6,1,2],[2,3,5,8]])

array([[5, 6, 1, 2],
 [2, 3, 5, 8]])

In [11]:
x = np.array([4,6,8,2])
x.ndim
x.shape
x.size
x.dtype
type(x)

numpy.ndarray

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(4,dtype=int)

array([0, 0, 0, 0])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.full((2,4),3)

array([[3, 3, 3, 3],
 [3, 3, 3, 3]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
 [0., 1., 0.],
 [0., 0., 1.]])

In [17]:
np.arange(1,20,2)

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

In [18]:
np.linspace(0,1,10)

array([0. , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
 0.55555556, 0.66666667, 0.77777778, 0.88888889, 1. ])

In [21]:
np.random.randint(2,10,9)

array([9, 4, 4, 4, 2, 6, 9, 6, 6])

In [22]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1]
a[5::]
a[3:7]
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]])

In [32]:
arr[0]
arr[1,2]
arr[2][2::]

array([11, 12])

In [33]:
arr1 = np.array([[3,4,5,2],[2,3,4,7],[9,8,1,4]])
arr1

array([[3, 4, 5, 2],
 [2, 3, 4, 7],
 [9, 8, 1, 4]])

In [34]:
arr>2

array([[False, False, True, True],
 [ True, True, True, True],
 [ True, True, True, True]])

In [35]:
arr>arr1

array([[False, False, False, True],
 [ True, True, True, True],
 [False, True, True, True]])

In [36]:
arr1[arr>2]

array([5, 2, 2, 3, 4, 7, 9, 8, 1, 4])

In [3]:
ab = np.random.randint(20, size=(4,5))
ab

array([[ 4, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [4]:
sub_ab = ab[:2,:3]
sub_ab

array([[4, 5, 2],
 [8, 7, 4]])

In [5]:
sub_ab[0,0] = 55
sub_ab

array([[55, 5, 2],
 [ 8, 7, 4]])

In [6]:
ab

array([[55, 5, 2, 10, 4],
 [ 8, 7, 4, 19, 8],
 [ 6, 13, 12, 10, 13],
 [ 9, 4, 17, 5, 12]])

In [8]:
n = np.arange(1,10)
n
n.shape

(9,)

In [9]:
n_shape = n.reshape(3,3)
n_shape

array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [13]:
ab.reshape(-1)
ab
ab.flatten()

array([55, 5, 2, 10, 4, 8, 7, 4, 19, 8, 6, 13, 12, 10, 13, 9, 4,
 17, 5, 12])

In [3]:
#29 Jan
a = np.array([10,11,12])
b = np.array([20,21,22])
np.concatenate([a,b])

array([10, 11, 12, 20, 21, 22])

In [5]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[11,12,13],[14,15,16]])
np.concatenate([a1,a2])

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [11, 12, 13],
 [14, 15, 16]])

In [6]:
np.concatenate([a1,a2],axis=1)

array([[ 1, 2, 3, 11, 12, 13],
 [ 4, 5, 6, 14, 15, 16]])

In [7]:
n1 = np.array([1,3,5,7,34,645,12,21])
n1

array([ 1, 3, 5, 7, 34, 645, 12, 21])

In [11]:
q,w,e = np.split(n1,[3,6])
q

array([1, 3, 5])

In [12]:
w

array([ 7, 34, 645])

In [13]:
e

array([12, 21])

In [14]:
d1 = np.arange(28).reshape(7,4)
d1

array([[ 0, 1, 2, 3],
 [ 4, 5, 6, 7],
 [ 8, 9, 10, 11],
 [12, 13, 14, 15],
 [16, 17, 18, 19],
 [20, 21, 22, 23],
 [24, 25, 26, 27]])

In [15]:
np.split(d1,[2,5])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[20, 21, 22, 23],
        [24, 25, 26, 27]])]

In [16]:
np.hsplit(d1,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21],
        [24, 25]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23],
        [26, 27]])]

In [17]:
np.sort(n1)

array([ 1, 3, 5, 7, 12, 21, 34, 645])

In [18]:
n1

array([ 1, 3, 5, 7, 34, 645, 12, 21])

In [20]:
n1.sort()
n1

array([ 1, 3, 5, 7, 12, 21, 34, 645])

In [21]:
-np.sort(-n1)

array([645, 34, 21, 12, 7, 5, 3, 1])

In [22]:
z = np.linspace(0,50,12,dtype="int").reshape(4,3)
z

array([[ 0, 4, 9],
 [13, 18, 22],
 [27, 31, 36],
 [40, 45, 50]])

In [23]:
m = np.array([1,0,-1])
m

array([ 1, 0, -1])

In [24]:
z + m

array([[ 1, 4, 8],
 [14, 18, 21],
 [28, 31, 35],
 [41, 45, 49]])

In [25]:
mat = np.array([1,2,3,4,5,6,7,8,9])
mat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
mat-5

array([-4, -3, -2, -1, 0, 1, 2, 3, 4])

In [29]:
mat *3

array([ 3, 6, 9, 12, 15, 18, 21, 24, 27])

In [30]:
fun = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
fun

array([[ 1, 2, 3],
 [ 4, 5, 6],
 [ 7, 8, 9],
 [10, 11, 12]])

In [31]:
np.add(fun,2)

array([[ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11],
 [12, 13, 14]])

In [32]:
np.subtract(fun,1)

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11]])

In [33]:
np.power(fun,2)

array([[ 1, 4, 9],
 [ 16, 25, 36],
 [ 49, 64, 81],
 [100, 121, 144]])

In [34]:
np.mean(fun)

6.5

In [35]:
np.sum(fun)

78

In [36]:
np.min(fun)

1

In [37]:
np.var(fun)

11.916666666666666

In [38]:
np.std(fun)

3.452052529534663

In [39]:
np.absolute(np.array([-1,2,-4,-49,-2]))

array([ 1, 2, 4, 49, 2])

In [40]:
np.log(fun)

array([[0. , 0.69314718, 1.09861229],
 [1.38629436, 1.60943791, 1.79175947],
 [1.94591015, 2.07944154, 2.19722458],
 [2.30258509, 2.39789527, 2.48490665]])

In [41]:
np.log10(fun)

array([[0. , 0.30103 , 0.47712125],
 [0.60205999, 0.69897 , 0.77815125],
 [0.84509804, 0.90308999, 0.95424251],
 [1. , 1.04139269, 1.07918125]])

In [ ]:
'''Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10. Go to the editor
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]'''

In [42]:
'''Write a NumPy program to create a 2d array with 1 on the border and 0 inside. Go to the editor
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

1 1 1 1 1
1 0 0 0 1
1 1 1 1 1'''
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
'''Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order. Go to the editor
Expected Output:
Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]'''

In [43]:
'''Write a NumPy program to convert a NumPy array of float values to a NumPy array of integer values. Go to the editor
Expected Output:
Original array elements:
[[ 12. 12.51]
[ 2.34 7.98]
[ 25.23 36.5 ]]
Convert float values to intger values:
[[12 12]
[ 2 7]
[25 36]]'''
import numpy as np
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print("Original array elements:")
print(x)
print("Convert float values to integer values:")
print(x.astype(int))

Original array elements:
[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
Convert float values to integer values:
[[12 12]
 [ 2  7]
 [25 36]]


In [2]:
#11 Feb - Pandas
import pandas as pd

In [5]:
#Creating Pandas Series
s = pd.Series([1,2,3,4,5])

In [6]:
type(s)

pandas.core.series.Series

In [7]:
s.axes

[RangeIndex(start=0, stop=5, step=1)]

In [8]:
s.dtype

dtype('int64')

In [10]:
s.ndim

1

In [11]:
s.size

5

In [12]:
s.values

array([1, 2, 3, 4, 5])

In [13]:
s.head(2)

0 1
1 2
dtype: int64

In [14]:
s.tail(3)

2 3
3 4
4 5
dtype: int64

In [16]:
s[1]

2

In [17]:
#Changing Index Labels
pd.Series([13,214,210,440,53])

0 13
1 214
2 210
3 440
4 53
dtype: int64

In [18]:
pd.Series([13,214,210,440,53],index=[4,6,7,3,87])

4 13
6 214
7 210
3 440
87 53
dtype: int64

In [20]:
#Creating series with key/value objects
age = {"Sathish":31, "Vignesh":41,"Swathi":22}
age

{'Sathish': 31, 'Vignesh': 41, 'Swathi': 22}

In [21]:
pd.Series(age)

Sathish 31
Vignesh 41
Swathi 22
dtype: int64

In [22]:
#Merging two different Series
s1 = pd.Series([2,3,55,2,6,44])
s2 = pd.Series([431,653,2435,2,1,87,3])
pd.concat([s1,s2])

0 2
1 3
2 55
3 2
4 6
5 44
0 431
1 653
2 2435
3 2
4 1
5 87
6 3
dtype: int64

In [23]:
s1[1]

3

In [24]:
s2[0:4]

0 431
1 653
2 2435
3 2
dtype: int64

In [25]:
#Queries in Pandas Series
3 in s1

True

In [31]:
#Data Frames
dataframe = pd.DataFrame({'Name':["Ajay","Faizal","Mani"],'Age':[23,53,12]})

In [32]:
dataframe["Age"]

0 23
1 53
2 12
Name: Age, dtype: int64

In [33]:
dataframe.Age

0 23
1 53
2 12
Name: Age, dtype: int64

In [37]:
import numpy as np
arr = np.array([5,4,2,7,1,8,6,4,3]).reshape(3,3,)
arr

array([[5, 4, 2],
 [7, 1, 8],
 [6, 4, 3]])

In [42]:
df = pd.DataFrame(arr,columns=["variable1","variable2","variable3"])

In [44]:
#changing column names
df.columns=("Var1","Var2","Var3")
df

Var1 
 Var2 
 Var3 
 
 
 
 
 0 
 5 
 4 
 2 
 
 
 1 
 7 
 1 
 8 
 
 
 2 
 6 
 4 
 3

In [45]:
df = pd.DataFrame({'Name':["Ajay","Faizal","Mani"],'Income':[7445432,324325,463523],'Age':[23,53,12]})
df

Name 
 Income 
 Age 
 
 
 
 
 0 
 Ajay 
 7445432 
 23 
 
 
 1 
 Faizal 
 324325 
 53 
 
 
 2 
 Mani 
 463523 
 12

In [46]:
df.iloc[0]

Name Ajay
Income 7445432
Age 23
Name: 0, dtype: object

In [47]:
df.iloc[[0,2]]

Name 
 Income 
 Age 
 
 
 
 
 0 
 Ajay 
 7445432 
 23 
 
 
 2 
 Mani 
 463523 
 12

In [3]:
#Merging Dataframes
#concat fn
import pandas as pd
emp = pd.DataFrame({"Name":["Sathish","Suresh","Dilli","Vijay"],
                    "Dep":["IT","Finance","HR","Delivery"],
                    "Salary":[34666,234211,53422,124232],
                    "Age":[24,29,54,31]})
emp

Name 
 Dep 
 Salary 
 Age 
 
 
 
 
 0 
 Sathish 
 IT 
 34666 
 24 
 
 
 1 
 Suresh 
 Finance 
 234211 
 29 
 
 
 2 
 Dilli 
 HR 
 53422 
 54 
 
 
 3 
 Vijay 
 Delivery 
 124232 
 31

In [4]:
emp1 = pd.DataFrame({"Name":["Jeessy","Kalki","Diya","Abinaya"],
                    "Dep":["IT","Finance","HR","Delivery"],
                    "Salary":[23465,234341,53345,163663],
                    "Age":[23,27,32,21]})
emp1

Name 
 Dep 
 Salary 
 Age 
 
 
 
 
 0 
 Jeessy 
 IT 
 23465 
 23 
 
 
 1 
 Kalki 
 Finance 
 234341 
 27 
 
 
 2 
 Diya 
 HR 
 53345 
 32 
 
 
 3 
 Abinaya 
 Delivery 
 163663 
 21

In [5]:
pd.concat([emp,emp1])

Name 
 Dep 
 Salary 
 Age 
 
 
 
 
 0 
 Sathish 
 IT 
 34666 
 24 
 
 
 1 
 Suresh 
 Finance 
 234211 
 29 
 
 
 2 
 Dilli 
 HR 
 53422 
 54 
 
 
 3 
 Vijay 
 Delivery 
 124232 
 31 
 
 
 0 
 Jeessy 
 IT 
 23465 
 23 
 
 
 1 
 Kalki 
 Finance 
 234341 
 27 
 
 
 2 
 Diya 
 HR 
 53345 
 32 
 
 
 3 
 Abinaya 
 Delivery 
 163663 
 21

In [6]:
pd.concat([emp,emp1],ignore_index=True)

Name 
 Dep 
 Salary 
 Age 
 
 
 
 
 0 
 Sathish 
 IT 
 34666 
 24 
 
 
 1 
 Suresh 
 Finance 
 234211 
 29 
 
 
 2 
 Dilli 
 HR 
 53422 
 54 
 
 
 3 
 Vijay 
 Delivery 
 124232 
 31 
 
 
 4 
 Jeessy 
 IT 
 23465 
 23 
 
 
 5 
 Kalki 
 Finance 
 234341 
 27 
 
 
 6 
 Diya 
 HR 
 53345 
 32 
 
 
 7 
 Abinaya 
 Delivery 
 163663 
 21

In [8]:
pd.concat([emp,emp1],join="inner")

Name 
 Dep 
 Salary 
 Age 
 
 
 
 
 0 
 Sathish 
 IT 
 34666 
 24 
 
 
 1 
 Suresh 
 Finance 
 234211 
 29 
 
 
 2 
 Dilli 
 HR 
 53422 
 54 
 
 
 3 
 Vijay 
 Delivery 
 124232 
 31 
 
 
 0 
 Jeessy 
 IT 
 23465 
 23 
 
 
 1 
 Kalki 
 Finance 
 234341 
 27 
 
 
 2 
 Diya 
 HR 
 53345 
 32 
 
 
 3 
 Abinaya 
 Delivery 
 163663 
 21

In [11]:
class1= pd.DataFrame({"Name":["Mike","Ana","Janiel"],"Student Number":[32212354,9364859,847937250],"GPA":[3.40,2.78,3.01]})
class1

Name 
 Student Number 
 GPA 
 
 
 
 
 0 
 Mike 
 32212354 
 3.40 
 
 
 1 
 Ana 
 9364859 
 2.78 
 
 
 2 
 Janiel 
 847937250 
 3.01

In [15]:
class2= pd.DataFrame({"Name":["Kristina","Michael","Arhun"],"Student Number":[738273948,422413342,938674938],"Age":[21,24,19]})
class2

Name 
 Student Number 
 Age 
 
 
 
 
 0 
 Kristina 
 738273948 
 21 
 
 
 1 
 Michael 
 422413342 
 24 
 
 
 2 
 Arhun 
 938674938 
 19

In [16]:
pd.concat([class1,class2],join="inner")

Name 
 Student Number 
 
 
 
 
 0 
 Mike 
 32212354 
 
 
 1 
 Ana 
 9364859 
 
 
 2 
 Janiel 
 847937250 
 
 
 0 
 Kristina 
 738273948 
 
 
 1 
 Michael 
 422413342 
 
 
 2 
 Arhun 
 938674938

In [17]:
pd.concat([class1,class2],join="outer")

Name 
 Student Number 
 GPA 
 Age 
 
 
 
 
 0 
 Mike 
 32212354 
 3.40 
 NaN 
 
 
 1 
 Ana 
 9364859 
 2.78 
 NaN 
 
 
 2 
 Janiel 
 847937250 
 3.01 
 NaN 
 
 
 0 
 Kristina 
 738273948 
 NaN 
 21.0 
 
 
 1 
 Michael 
 422413342 
 NaN 
 24.0 
 
 
 2 
 Arhun 
 938674938 
 NaN 
 19.0

In [18]:
pd.merge(class1,class2,how="left")

Name 
 Student Number 
 GPA 
 Age 
 
 
 
 
 0 
 Mike 
 32212354 
 3.40 
 NaN 
 
 
 1 
 Ana 
 9364859 
 2.78 
 NaN 
 
 
 2 
 Janiel 
 847937250 
 3.01 
 NaN

In [19]:
pd.merge(class1,class2,how="right")

Name 
 Student Number 
 GPA 
 Age 
 
 
 
 
 0 
 Kristina 
 738273948 
 NaN 
 21 
 
 
 1 
 Michael 
 422413342 
 NaN 
 24 
 
 
 2 
 Arhun 
 938674938 
 NaN 
 19

In [20]:
#Append
class1.append(class2,ignore_index=True)

Name 
 Student Number 
 GPA 
 Age 
 
 
 
 
 0 
 Mike 
 32212354 
 3.40 
 NaN 
 
 
 1 
 Ana 
 9364859 
 2.78 
 NaN 
 
 
 2 
 Janiel 
 847937250 
 3.01 
 NaN 
 
 
 3 
 Kristina 
 738273948 
 NaN 
 21.0 
 
 
 4 
 Michael 
 422413342 
 NaN 
 24.0 
 
 
 5 
 Arhun 
 938674938 
 NaN 
 19.0

In [21]:
#Sorting
class1.sort_values(by="Name")

Name 
 Student Number 
 GPA 
 
 
 
 
 1 
 Ana 
 9364859 
 2.78 
 
 
 2 
 Janiel 
 847937250 
 3.01 
 
 
 0 
 Mike 
 32212354 
 3.40

In [22]:
#Aggreagation Functions
employees = pd.DataFrame({"Name":["Josh","Mike","Julia","Sergio","Julia","Michael","Sarath","Jakub","Chris"],
                          "Department":["IT","Human Resources","Finance","Supply Chain","Finance","Marketing","IT","Human Resources","Law"],
                          "Income":[4800,5200,6600,5700,7200,8400,7700,4200,9400],
                          "Age":[24,28,33,41,22,46,31,27,39],
                          "Experience":[2,5,9,17,1,24,10,6,13]})
employees

Name 
 Department 
 Income 
 Age 
 Experience 
 
 
 
 
 0 
 Josh 
 IT 
 4800 
 24 
 2 
 
 
 1 
 Mike 
 Human Resources 
 5200 
 28 
 5 
 
 
 2 
 Julia 
 Finance 
 6600 
 33 
 9 
 
 
 3 
 Sergio 
 Supply Chain 
 5700 
 41 
 17 
 
 
 4 
 Julia 
 Finance 
 7200 
 22 
 1 
 
 
 5 
 Michael 
 Marketing 
 8400 
 46 
 24 
 
 
 6 
 Sarath 
 IT 
 7700 
 31 
 10 
 
 
 7 
 Jakub 
 Human Resources 
 4200 
 27 
 6 
 
 
 8 
 Chris 
 Law 
 9400 
 39 
 13

In [23]:
employees.count()

Name 9
Department 9
Income 9
Age 9
Experience 9
dtype: int64

In [26]:
employees["Department"].value_counts()

IT 2
Human Resources 2
Finance 2
Supply Chain 1
Marketing 1
Law 1
Name: Department, dtype: int64

In [27]:
employees.mean()

<ipython-input-27-54586efc808d>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  employees.mean()


Income 6577.777778
Age 32.333333
Experience 9.666667
dtype: float64

In [28]:
employees.median()

<ipython-input-28-8010e1878e06>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  employees.median()


Income 6600.0
Age 31.0
Experience 9.0
dtype: float64

In [29]:
employees.sum()

Name JoshMikeJuliaSergioJuliaMichaelSarathJakubChris
Department ITHuman ResourcesFinanceSupply ChainFinanceMar...
Income 59200
Age 291
Experience 87
dtype: object

In [30]:
employees.min()

Name Chris
Department Finance
Income 4200
Age 22
Experience 1
dtype: object

In [31]:
employees.max()

Name Sergio
Department Supply Chain
Income 9400
Age 46
Experience 24
dtype: object

In [32]:
employees.std()

<ipython-input-32-561b13b4ed81>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  employees.std()


Income 1746.981524
Age 8.154753
Experience 7.416198
dtype: float64

In [33]:
employees.var()

<ipython-input-33-c383542361dd>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  employees.var()


Income 3.051944e+06
Age 6.650000e+01
Experience 5.500000e+01
dtype: float64

In [34]:
employees.describe()

Income 
 Age 
 Experience 
 
 
 
 
 count 
 9.000000 
 9.000000 
 9.000000 
 
 
 mean 
 6577.777778 
 32.333333 
 9.666667 
 
 
 std 
 1746.981524 
 8.154753 
 7.416198 
 
 
 min 
 4200.000000 
 22.000000 
 1.000000 
 
 
 25% 
 5200.000000 
 27.000000 
 5.000000 
 
 
 50% 
 6600.000000 
 31.000000 
 9.000000 
 
 
 75% 
 7700.000000 
 39.000000 
 13.000000 
 
 
 max 
 9400.000000 
 46.000000 
 24.000000

In [35]:
employees.describe().T

count 
 mean 
 std 
 min 
 25% 
 50% 
 75% 
 max 
 
 
 
 
 Income 
 9.0 
 6577.777778 
 1746.981524 
 4200.0 
 5200.0 
 6600.0 
 7700.0 
 9400.0 
 
 
 Age 
 9.0 
 32.333333 
 8.154753 
 22.0 
 27.0 
 31.0 
 39.0 
 46.0 
 
 
 Experience 
 9.0 
 9.666667 
 7.416198 
 1.0 
 5.0 
 9.0 
 13.0 
 24.0

In [36]:
employees.sem()

<ipython-input-36-c34e3d6562b9>:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  employees.sem()


Income 582.327175
Age 2.718251
Experience 2.472066
dtype: float64

In [37]:
#Groupings
employees = pd.DataFrame({"Name":["Josh","Mike","Julia","Sergio","Julia","Michael","Sarath","Jakub","Chris"],
                          "Department":["IT","Human Resources","Finance","Supply Chain","Finance","Marketing","IT","Human Resources","Law"],
                          "Income":[4800,5200,6600,5700,7200,8400,7700,4200,9400],
                          "Age":[24,28,33,41,22,46,31,27,39],
                          "Experience":[2,5,9,17,1,24,10,6,13]})
employees

Name 
 Department 
 Income 
 Age 
 Experience 
 
 
 
 
 0 
 Josh 
 IT 
 4800 
 24 
 2 
 
 
 1 
 Mike 
 Human Resources 
 5200 
 28 
 5 
 
 
 2 
 Julia 
 Finance 
 6600 
 33 
 9 
 
 
 3 
 Sergio 
 Supply Chain 
 5700 
 41 
 17 
 
 
 4 
 Julia 
 Finance 
 7200 
 22 
 1 
 
 
 5 
 Michael 
 Marketing 
 8400 
 46 
 24 
 
 
 6 
 Sarath 
 IT 
 7700 
 31 
 10 
 
 
 7 
 Jakub 
 Human Resources 
 4200 
 27 
 6 
 
 
 8 
 Chris 
 Law 
 9400 
 39 
 13

In [38]:
employees.groupby("Department")

In [39]:
emp_dep = employees.groupby("Department")
emp_dep.get_group("IT")

Name 
 Department 
 Income 
 Age 
 Experience 
 
 
 
 
 0 
 Josh 
 IT 
 4800 
 24 
 2 
 
 
 6 
 Sarath 
 IT 
 7700 
 31 
 10

In [40]:
employees.groupby("Department").sum()

Income 
 Age 
 Experience 
 
 
 Department 
 
 
 
 
 
 
 
 Finance 
 13800 
 55 
 10 
 
 
 Human Resources 
 9400 
 55 
 11 
 
 
 IT 
 12500 
 55 
 12 
 
 
 Law 
 9400 
 39 
 13 
 
 
 Marketing 
 8400 
 46 
 24 
 
 
 Supply Chain 
 5700 
 41 
 17

In [42]:
employees.groupby("Department").mean()["Income"]

Department
Finance 6900.0
Human Resources 4700.0
IT 6250.0
Law 9400.0
Marketing 8400.0
Supply Chain 5700.0
Name: Income, dtype: float64

In [43]:
employees.groupby("Department")["Income"].agg(["mean","max","median"])

mean 
 max 
 median 
 
 
 Department 
 
 
 
 
 
 
 
 Finance 
 6900.0 
 7200 
 6900.0 
 
 
 Human Resources 
 4700.0 
 5200 
 4700.0 
 
 
 IT 
 6250.0 
 7700 
 6250.0 
 
 
 Law 
 9400.0 
 9400 
 9400.0 
 
 
 Marketing 
 8400.0 
 8400 
 8400.0 
 
 
 Supply Chain 
 5700.0 
 5700 
 5700.0

In [44]:
def salary_increase(x):
    return x+10000

In [45]:
employees["Income"]

0 4800
1 5200
2 6600
3 5700
4 7200
5 8400
6 7700
7 4200
8 9400
Name: Income, dtype: int64

In [47]:
employees["Income"].transform(salary_increase)

0 14800
1 15200
2 16600
3 15700
4 17200
5 18400
6 17700
7 14200
8 19400
Name: Income, dtype: int64

In [48]:
employees["Name"].apply(len)

0 4
1 4
2 5
3 6
4 5
5 7
6 6
7 5
8 5
Name: Name, dtype: int64

In [49]:
def age(x):
    return x+1

In [50]:
employees["Age"].apply(age)

0 25
1 29
2 34
3 42
4 23
5 47
6 32
7 28
8 40
Name: Age, dtype: int64

In [52]:
employees["Department"].replace({"IT":"Information Technology"},inplace=True)
employees

Name 
 Department 
 Income 
 Age 
 Experience 
 
 
 
 
 0 
 Josh 
 Information Technology 
 4800 
 24 
 2 
 
 
 1 
 Mike 
 Human Resources 
 5200 
 28 
 5 
 
 
 2 
 Julia 
 Finance 
 6600 
 33 
 9 
 
 
 3 
 Sergio 
 Supply Chain 
 5700 
 41 
 17 
 
 
 4 
 Julia 
 Finance 
 7200 
 22 
 1 
 
 
 5 
 Michael 
 Marketing 
 8400 
 46 
 24 
 
 
 6 
 Sarath 
 Information Technology 
 7700 
 31 
 10 
 
 
 7 
 Jakub 
 Human Resources 
 4200 
 27 
 6 
 
 
 8 
 Chris 
 Law 
 9400 
 39 
 13

In [54]:
nba = pd.read_csv("nba.csv")

In [55]:
nba.head()

Name 
 Team 
 Number 
 Position 
 Age 
 Height 
 Weight 
 College 
 Salary 
 
 
 
 
 0 
 Avery Bradley 
 Boston Celtics 
 0.0 
 PG 
 25.0 
 6-2 
 180.0 
 Texas 
 7730337.0 
 
 
 1 
 Jae Crowder 
 Boston Celtics 
 99.0 
 SF 
 25.0 
 6-6 
 235.0 
 Marquette 
 6796117.0 
 
 
 2 
 John Holland 
 Boston Celtics 
 30.0 
 SG 
 27.0 
 6-5 
 205.0 
 Boston University 
 NaN 
 
 
 3 
 R.J. Hunter 
 Boston Celtics 
 28.0 
 SG 
 22.0 
 6-5 
 185.0 
 Georgia State 
 1148640.0 
 
 
 4 
 Jonas Jerebko 
 Boston Celtics 
 8.0 
 PF 
 29.0 
 6-10 
 231.0 
 NaN 
 5000000.0

In [57]:
nba.shape

(458, 9)

In [58]:
nba.info

<bound method DataFrame.info of               Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Te

In [59]:
nba.describe()

Number 
 Age 
 Weight 
 Salary 
 
 
 
 
 count 
 457.000000 
 457.000000 
 457.000000 
 4.460000e+02 
 
 
 mean 
 17.678337 
 26.938731 
 221.522976 
 4.842684e+06 
 
 
 std 
 15.966090 
 4.404016 
 26.368343 
 5.229238e+06 
 
 
 min 
 0.000000 
 19.000000 
 161.000000 
 3.088800e+04 
 
 
 25% 
 5.000000 
 24.000000 
 200.000000 
 1.044792e+06 
 
 
 50% 
 13.000000 
 26.000000 
 220.000000 
 2.839073e+06 
 
 
 75% 
 25.000000 
 30.000000 
 240.000000 
 6.500000e+06 
 
 
 max 
 99.000000 
 40.000000 
 307.000000 
 2.500000e+07

In [60]:
nba.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [61]:
nba.nunique()

Name 457
Team 30
Number 53
Position 5
Age 22
Height 18
Weight 87
College 118
Salary 309
dtype: int64

In [64]:
nba[nba["Position"]=="PG"]

Name 
 Team 
 Number 
 Position 
 Age 
 Height 
 Weight 
 College 
 Salary 
 
 
 
 
 0 
 Avery Bradley 
 Boston Celtics 
 0.0 
 PG 
 25.0 
 6-2 
 180.0 
 Texas 
 7730337.0 
 
 
 8 
 Terry Rozier 
 Boston Celtics 
 12.0 
 PG 
 22.0 
 6-2 
 190.0 
 Louisville 
 1824360.0 
 
 
 9 
 Marcus Smart 
 Boston Celtics 
 36.0 
 PG 
 22.0 
 6-4 
 220.0 
 Oklahoma State 
 3431040.0 
 
 
 11 
 Isaiah Thomas 
 Boston Celtics 
 4.0 
 PG 
 27.0 
 5-9 
 185.0 
 Washington 
 6912869.0 
 
 
 19 
 Jarrett Jack 
 Brooklyn Nets 
 2.0 
 PG 
 32.0 
 6-3 
 200.0 
 Georgia Tech 
 6300000.0 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 440 
 Brian Roberts 
 Portland Trail Blazers 
 2.0 
 PG 
 30.0 
 6-1 
 173.0 
 Dayton 
 2854940.0 
 
 
 443 
 Trey Burke 
 Utah Jazz 
 3.0 
 PG 
 23.0 
 6-1 
 191.0 
 Michigan 
 2658240.0 
 
 
 445 
 Dante Exum 
 Utah Jazz 
 11.0 
 PG 
 20.0 
 6-6 
 190.0 
 NaN 
 3777720.0 
 
 
 453 
 Shelvin Mack 
 Utah Jazz 
 8.0 
 PG 
 26.0 
 6-3 
 203.0 
 Butler 
 2433333.0 
 
 
 454 
 Raul Neto 
 Utah Jazz 
 25.0 
 PG 
 24.0 
 6-1 
 179.0 
 NaN 
 900000.0 
 
 
 
 92 rows × 9 columns

In [1]:
#Data Processing
import pandas as pd
import numpy as np
import math
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.neighbors import LocalOutlierFactor
import missingno as msno
from ycimpute.imputer import knnimput
from ycimpute.imputer import iterforest
from ycimpute.imputer import EM
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [4]:
df = sns.load_dataset("diamonds")
df = df.select_dtypes(include=["float64","int64"])
df.dropna(inplace=True)
df.head()

carat 
 depth 
 table 
 price 
 x 
 y 
 z 
 
 
 
 
 0 
 0.23 
 61.5 
 55.0 
 326 
 3.95 
 3.98 
 2.43 
 
 
 1 
 0.21 
 59.8 
 61.0 
 326 
 3.89 
 3.84 
 2.31 
 
 
 2 
 0.23 
 56.9 
 65.0 
 327 
 4.05 
 4.07 
 2.31 
 
 
 3 
 0.29 
 62.4 
 58.0 
 334 
 4.20 
 4.23 
 2.63 
 
 
 4 
 0.31 
 63.3 
 58.0 
 335 
 4.34 
 4.35 
 2.75

In [5]:
df.shape

(53940, 7)

In [6]:
df.describe()

carat 
 depth 
 table 
 price 
 x 
 y 
 z 
 
 
 
 
 count 
 53940.000000 
 53940.000000 
 53940.000000 
 53940.000000 
 53940.000000 
 53940.000000 
 53940.000000 
 
 
 mean 
 0.797940 
 61.749405 
 57.457184 
 3932.799722 
 5.731157 
 5.734526 
 3.538734 
 
 
 std 
 0.474011 
 1.432621 
 2.234491 
 3989.439738 
 1.121761 
 1.142135 
 0.705699 
 
 
 min 
 0.200000 
 43.000000 
 43.000000 
 326.000000 
 0.000000 
 0.000000 
 0.000000 
 
 
 25% 
 0.400000 
 61.000000 
 56.000000 
 950.000000 
 4.710000 
 4.720000 
 2.910000 
 
 
 50% 
 0.700000 
 61.800000 
 57.000000 
 2401.000000 
 5.700000 
 5.710000 
 3.530000 
 
 
 75% 
 1.040000 
 62.500000 
 59.000000 
 5324.250000 
 6.540000 
 6.540000 
 4.040000 
 
 
 max 
 5.010000 
 79.000000 
 95.000000 
 18823.000000 
 10.740000 
 58.900000 
 31.800000

In [7]:
quart1 = df.quantile(0.25)
quart2 = df.quantile(0.75)
IQR = quart2-quart1
print(quart1)
print(quart2)
print(IQR)

carat      0.40
depth     61.00
table     56.00
price    950.00
x          4.71
y          4.72
z          2.91
Name: 0.25, dtype: float64
carat       1.04
depth      62.50
table      59.00
price    5324.25
x           6.54
y           6.54
z           4.04
Name: 0.75, dtype: float64
carat       0.64
depth       1.50
table       3.00
price    4374.25
x           1.83
y           1.82
z           1.13
dtype: float64


In [10]:
l_i_f = quart1 - 1.5*IQR 
u_i_f = quart2 + 1.5*IQR
print(l_i_f)
print(u_i_f)

carat      -0.560
depth      58.750
table      51.500
price   -5611.375
x           1.965
y           1.990
z           1.215
dtype: float64
carat        2.000
depth       64.750
table       63.500
price    11885.625
x            9.285
y            9.270
z            5.735
dtype: float64


In [11]:
print("Outliers:",len(df[(df<l_i_f) | (df>u_i_f)]))

Outliers: 53940
